### PR TITLE
Add version info and update some visuals

### PR DESCRIPTION
**Pull request by HON95**
### Status

- [X] Done
- [ ] Work in progress
- [ ] Needs testing from others

### Checklist

- [x] The code is linted
- [ ] My changes requires change to the documentation.
- [ ] I have updated the documentation.
- [x] I have introduced changes to build configuration.

#### Added
- Added version info to the app, shown in the site footer.
- Added video frame to LAN.
- Added link(s) to active LAN(s) on front page.
- Added links to both user profile and LAN seating in the arrivals list.
- Added LAN listing for competitions.
- Added instructions for changing email address and password.
- Lottery now throws out all participants (but keeps winners) if the lottery does not have multiple winnings.
- Slightly prettier email templates.

#### Changed
- Made footer prettier.
- Removed user info from sidebar.
- Made news list pages single-column and less wasteful of space.
- Made sponsor page prettier.
- Made breadcrumbs more consistent and changed which pages show them.
- Made page headers visually more consistent and appropriate.
- Replaced logo images with higher-definition versions (but same graphics).

#### Removed
- Removed unique email check from register form, since email addresses are non-unique.

#### Fixed
- Fixed HTML DOM bug in the seating app template.
- Fixed seating map size inconsistency across browsers.
- Fixed account recovery sending recovery emails to only one account for a certain email address.

### Screenshots
[Outdated screenshots](https://imgur.com/a/eSjPTID)

### CODE REVIEW

**Comment by HON95** [comment]
The "competition info" section if the sidebar seems somewhat useless too.

**Comment by HON95** [comment]
Mobile view still looks terrible, with the sidebar and too much spacing.

**Comment by HON95** [comment]
1. I tried with a background and with a background inside a visible frame for the sponsor images, but that looked bad for all the images with non-white foreground and images with non-transparent white backgrounds. So no, I didn't find a fix, but most orgs have a logo variant without white foreground. And we, as users, can just manually add a background to the image itself it looks bad on a white background.
2. I agree that one link of some sort would looks better, but apparently, the news/front page shows news from _all_ (up to multiple) upcoming and current LANs, so a table just made more sense looking just at the code. We could replace the table with a single link when there's just one active LAN.

**Comment by larserikgk** [comment]
1. Ok, I agree.
2. Great, showing a single link with one active LAN would be nice.

**Comment by HON95** [comment]
I'm not sure what the best look would be for a single link. A simple line like "LAN: **ExampleLAN 2019 høst** (1. aug. 2020 – 1. sept. 2020)" above the news articles? And then a "LANs: <<list>>" if there are multiple?

**Comment by larserikgk** [comment]
Maybe just this format for single: "ExampleLAN 2019 høst (1. aug. 2020 – 1. sept. 2020)" and your suggestion for multiple

**Comment by HON95** [comment]
Like [this](https://imgur.com/a/tF5cM6p)? I added a header for both single and multiple, and the last one without header, for comparison.

**Comment by HON95** [comment]
The "LAN(s)" header is h2 while the news headers are h3, so it makes the page as a whole look a little more "complete".

**Comment by HON95** [comment]
But a little generic and useless too, for a single LAN. Idk.

**Comment by HON95** [comment]
I've added some more demo images [here](https://imgur.com/a/tF5cM6p).

**Comment by HON95** [comment]
It would be cool to have the promo vid and more details on the front page (if there is only one LAN), but that would be a whole redesign of the front/news page and the LAN details page. Which is doable, but a visible link to the event page is also fine.

**Comment by larserikgk** [comment]
I like the design with the button link to the lan page, looks good. Agree that we should have more visuals on the front page, but I agree that should be part of a bigger redesign

**Pull request merged**
