### PR TITLE
Add new Stripe integration that support SCA

### PR DESCRIPTION
**Pull request by larserikgk**
### Status

- [x] Done
- [ ] Work in progress
- [x] Needs testing from others

### Description
New payment flow for tickets using Stripe v3 API. Changes the usage of charges to use the new payment intent flow.

### Checklist

- [x] The code is linted
- [ ] My changes requires change to the documentation.
- [ ] I have updated the documentation.
- [ ] I have introduced changes to build configuration.

### Minor Changes
- Payment form is now moved to separate page after choosing ticket
- User is redirected back to lan page after payment status is settled

### Breaking Changes
- There are no translations for this change

### Other
I have tested a a bit with the cards at https://stripe.com/docs/payments/payment-intents/quickstart#testing and the test keys for Casual Gaming. I would prefer if someone else could review the logic and flow. As a new shop module is planned for the future, this change is implemented as a minimal working change.

### CODE REVIEW

**Comment by HON95** [comment]
About the payment/order page still being accessable when the user already has a ticket of that type: It _does_ add new tickets of the same type for the user, I was looking in the wrong place. And it does create new payments for each ticket (as expected).

**Comment by HON95** [comment]
Maybe add a description to payments? Like a line containing the username, ticket type and LAN, to make Stripe receipts (which are enabled for CaG) more descriptive.

**Comment by larserikgk** [comment]
Will take a look at the bugs and suggestions tomorrow. To answer the question: The server never touches the credit card info. The credit card is sent to Stripe via Stripe.js and a token is returned. The server then creates a charge on this token which in turn credits us with the cost of the ticket.

**Comment by HON95** [comment]
Okay, got it. And I like the new implementation, even though I'm super picky about some stuff. Are you using the management scripts in `manage/`, btw? `manage/check.sh` checks most stuff Travis CI checks, like linting.

**Comment by larserikgk** [comment]
I'm using Windows most days now, but the scripts you mentioned don't work out of the box in my Linux environment either.

**Comment by larserikgk** [comment]
My latest changes:

> The script can be moved to the script block.

Scripts have been moved to a separate file and included using the script block.

> Is the margin-bot-sm class necessary? Is seemingly doesn't do much.
> Most pages are col-md-9, not 6.
> Maybe make it more form-like, like the direct registration page?

The input fields look too big if they are 9 columns. In my opinion, this form layout looks better than the one that is used elsewhere. Should probably change it for consistency, but will ignore for now since studlan is slated for redesign/scrapping.

> Add translation tags, even though very few things are actually added translations for.

After some testing i realized that the translations have not been update since 2016, and this should be a separate issue as it is a big job. I will create an issue for it.

> The payment/order page is still accessable when the user already has a ticket of that type. Paying again gives the same success message, but doesn't add another ticket. I have no idea if it sends a new payment to Stripe.

This has been fixed. The user will be redirected to the LAN page if he has a ticket.

> Maybe add a notice about the payment being handled by Stripe, and that the sensitive card info does not go through the back-end? Since it's not visible anywhere how it's being processed now that we don't use the stock Stripe thingy.

I added a info page in English that explains the usage and links to Stripe documentation.

> Make the submit button a subit button, so enter to submit works.

What browser are you using? This works for me in Chrome(latest) on Windows.

**Comment by HON95** [comment]
Side note: All `manage/` scripts should work if `manage/setup.sh` is run first, which sets up the venv, adds the local settings file, migrates the Django DB, etc.

**Comment by HON95** [comment]
Oh, and another thing. Should we redirect to the seating map, if there is one, after buying a ticket, to make it extra obvious that they can reserve a seat with their ticket?

**Comment by larserikgk** [comment]
> I tested with both Chrome (latest?) and Firefox on Windows 10, enter didn't work in either. And my suggestion about making the button type=submit was pretty useless considering that this isn't a (conventional) form. I tried wrapping the whole thing in form (for reasons), but that just made pressing enter in the first field not work as intended. This isn't a too big problem, but if you want to try to fix it, maybe make it a form and tie the submit listener to the submit event instead?

Just tested in Firefox on win10, and seems to work fine here. I think we have differing expectations to how this should behave. My expectation is that when you tab to focus the buy-button and press enter, the form should submit. I am experiencing this expected(for me) behavior.

> The payment page is accessable if the user has not pressed attend (by going to the URL). Redirect with an error message.

Fixed.

> Users can unattend the event after buying a ticket (by POSTing to the unattend endpoint). Add a check for if the player has a ticket.

Fixed.

> Can you add a short comment to the if intent.status == 'requires_action' ... part in views.py explaining what it does or when it's called?

Fixed, see further down for an explanation.

> Consider logging the error for the "Payment unsuccessful - please contact support" message. The error file logger should catch errors in the django logger (or something like that).

Will have to revisit this later. There is currently not a single logging statement in the system, and I was not able to set up log handlers for custom modules.

> Can you remove the padding-bot-sm class from the HTML and margin-bot-sm class from the CSS? (They're not even the same, so they do absolutely nothing.)

Woops, fixed.

> Maybe wrap the input and the button in divs, to make them block elements. And add a br after the button (like you've done to the inputs) to add some spacing before the link below.

Fixed

> Maybe capitalize and remove the colon for "Cardholder name:" and "Card info:", since they're headers.

Removed colon, but refrained from capitalizing as I believe it is incorrect (and in conflict with the label "Card number" provided by the Stripe elements)

> Maybe add a placeholder (like "Cardholder name") in the card holder field.

Fixed

> Consider rephrasing the header, considering ticket names may be something like "ExampleLAN 2019 – VIP", which makes the title look strange and grammatically incorrect. Maybe add it to a line below instead, together with the ticket price (which is currently absent on the page). And make the header h1 if you make it shorter.

Fixed. Take a look at the new layout with a table to match the lan page better.

> Maybe make the info page col-md-9 since it's all text? And the header h1 with class page-header.

Fixed.

> How would BankID prompts and such work with this? I have no idea how it worked with the previous solution.

This is handled by Stripe. When action is required, views.py returns the correct status code along with the intent key. Stripe.js then handle SCA (3D secure, BankId ++) or whatever other action is required. You can test this functionality by using the card `4000002760003184` (name, date and cvc can be anything) with the Stripe test keys set in settings.

> Remember to add the change(s) to the changelog file (including fixing buying tickets without attending and unattending with ticket).

Fixed.

> Oh, and another thing. Should we redirect to the seating map, if there is one, after buying a ticket, to make it extra obvious that they can reserve a seat with their ticket?

As each lan can have multiple seatings and each ticket can be valid for multiple seatings i feel that this might feel arbitrary for the user.

**Comment by HON95** [comment]
I can fix the missing translations in the translation PR before merging it. The col-in-col thing too if you don't fix it first.

**Comment by HON95** [comment]
We _could_ push it to master/dev so we can test it a little more realistically (with HTTPS and all), then just make an issue with the problems found.

**Comment by HON95** [comment]
I notices we don't have a CSP, but adding one didn't fix the problem. [Apparently](https://www.reddit.com/r/webdev/comments/6tor75/stripejs_is_now_blocked_in_ghostery_killing_lots/), Ghostery blocks Stripe. We should probably add a notice for other people using Ghostery and similar extensions. So Firefox works for me now.

IE is still broken. It sends a request to api.stripe.com when pressing the button, and then nothing. No payment appears in Stripe.

**Comment by larserikgk** [comment]
I agree that we should get this to staging/test and fix the translations after your other to PRs have been merged in to avoid colossal conflicts.

**Comment by HON95** [comment]
I've got another check for your payment view: #284

**Pull request merged**
